FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN useradd -m -u 10001 runner


ENV NUGET_PACKAGES=/nuget-cache
RUN mkdir -p /nuget-cache /opt/proj \
    && cd /opt/proj \
    && dotnet new xunit --force \
    && dotnet restore \
    && rm -f UnitTest1.cs \
    && chmod -R 755 /nuget-cache /opt/proj

WORKDIR /workspace
USER runner

CMD ["dotnet", "--info"]
